[package]
name = "forest"
version = "0.1.0"
edition = "2021"
authors = ["Nicholas Crosbie"]
description = "See the forest for the trees."
license = "MIT"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
