[package]
name = "forest"
version = "0.1.0"
edition = "2021"
authors = ["Nicholas Crosbie"]
description = "A tool that provides a high-level summary of Rust projects"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
